version: "3.8"
services:
  api:
    build: api-server
    restart: always
    ports:
      - 5000:5000

    networks:
      - flask_network

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ftx
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: frontend-server
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - flask_network

networks:
  flask_network:

volumes:
  postgres_data:
